package com.daftar.app.domain.model

// Prototype v18 renamed the customer entry types to saraf-perspective wording:
// deposit → "You Received", withdrawal → "You Gave". The label used depends on
// the surface — feed rows, statements, and toasts each use their own variant.
enum class CustomerTxType(val label: String, val pashtoLabel: String) {
    OPENING("Opening balance", "پیلیز پاتي"),
    DEPOSIT("You Received", "جمع"),
    WITHDRAWAL("You Gave", "ایستل"),
    CHARGE("Charge on behalf", "په وکالت پیسې ورکړل"),
    CREDIT("Advance credit", "پیشکي پور");

    /** Debits reduce what the saraf owes the customer. */
    val isDebit: Boolean get() = this == WITHDRAWAL || this == CHARGE || this == CREDIT

    /** Ledger-feed row title (v18 activityFeed: charge → "Charge", credit → "Credit advance"). */
    val feedLabel: String
        get() = when (this) {
            CHARGE -> "Charge"
            CREDIT -> "Credit advance"
            else -> label
        }

    /** Statement / customer-history label (v18 statement rows: charge → "Paid on behalf"). */
    val statementLabel: String
        get() = if (this == CHARGE) "Paid on behalf" else label

    /** Plain accounting word — used by save toasts ("Deposit recorded · …") like v18. */
    val plainLabel: String
        get() = when (this) {
            OPENING -> "Opening"
            DEPOSIT -> "Deposit"
            WITHDRAWAL -> "Withdrawal"
            CHARGE -> "Charge"
            CREDIT -> "Credit"
        }
}

/** Cross-currency detail attached when cash was taken in one currency but booked in another. */
data class CurrencyConversion(
    val receivedAmount: Double,
    val receivedCurrency: String,
    val rate: Double,
    val creditedAmount: Double,
    val creditedCurrency: String,
)

data class CustomerTransaction(
    val id: String,
    val type: CustomerTxType,
    val amount: Double,
    val currency: String,
    val dateLabel: String,
    val timestampMillis: Long,
    val note: String? = null,
    /** Set when this entry was generated by an account-funded hawala (no cash moved). */
    val hawalaId: String? = null,
    val conversion: CurrencyConversion? = null,
    /** v20: attached receipt photos (content:// URIs) shown on You Received/You Gave and the detail. */
    val photoUris: List<String> = emptyList(),
) {
    /** Signed effect on the customer balance (positive = saraf owes customer). */
    val balanceDelta: Double
        get() = when (type) {
            CustomerTxType.DEPOSIT, CustomerTxType.OPENING -> amount
            else -> -amount
        }
}

/** An account-holding customer of the saraf. */
data class Customer(
    val id: String,
    val name: String,
    val shortName: String,
    val phone: String,
    val city: City,
    val colorIndex: Int,
    val initial: String,
    val accountOpenedLabel: String,
    val notes: String? = null,
    val transactions: List<CustomerTransaction> = emptyList(),
)
