package com.daftar.app.domain.model

enum class CustomerTxType(val label: String, val pashtoLabel: String) {
    OPENING("Opening balance", "پیلیز پاتي"),
    DEPOSIT("Deposit", "سپما"),
    WITHDRAWAL("Withdrawal", "ایستل"),
    CHARGE("Charge on behalf", "په وکالت پیسې ورکړل"),
    CREDIT("Advance credit", "پیشکي پور");

    /** Debits reduce what the saraf owes the customer. */
    val isDebit: Boolean get() = this == WITHDRAWAL || this == CHARGE || this == CREDIT
}

/** Cross-currency detail attached when cash was taken in one currency but booked in another. */
data class CurrencyConversion(
    val receivedAmount: Double,
    val receivedCurrency: String,
    val rate: Double,
    val creditedAmount: Double,
    val creditedCurrency: String,
)

data class CustomerTransaction(
    val id: String,
    val type: CustomerTxType,
    val amount: Double,
    val currency: String,
    val dateLabel: String,
    val timestampMillis: Long,
    val note: String? = null,
    /** Set when this entry was generated by an account-funded hawala (no cash moved). */
    val hawalaId: String? = null,
    val conversion: CurrencyConversion? = null,
) {
    /** Signed effect on the customer balance (positive = saraf owes customer). */
    val balanceDelta: Double
        get() = when (type) {
            CustomerTxType.DEPOSIT, CustomerTxType.OPENING -> amount
            else -> -amount
        }
}

/** An account-holding customer of the saraf. */
data class Customer(
    val id: String,
    val name: String,
    val shortName: String,
    val phone: String,
    val city: City,
    val colorIndex: Int,
    val initial: String,
    val accountOpenedLabel: String,
    val notes: String? = null,
    val transactions: List<CustomerTransaction> = emptyList(),
)
